"""SmartRoute service layer - re-exports from sub-modules.

This module maintains backward compatibility by re-exporting all public
functions from the split service modules.
"""
from __future__ import annotations

from services.adjustment_service import (
    add_intent_satisfied,
    adjustment_intent_satisfied,
    adjustment_search_terms,
    adjustment_status_for,
    adjustment_summary,
    build_changed_stops,
    choose_add_target,
    choose_adjustment_target,
    detect_adjustment_kind,
    find_adjustment_candidate,
    has_negative_adjustment,
    has_reduce_adjustment,
    is_core_route_stop,
    mentioned_categories,
    mentioned_stop_index,
    objective_improved,
    parse_adjustment_intent,
    suggested_relaxations_for,
)
from services.anchor_service import (
    categories_for_live_route,
    city_hint_from,
    clean_anchor_candidate,
    context_poi_to_poi,
    extract_anchor_text,
    fixed_start_pois_from_route,
    hard_pinned_pois_for_context,
    is_likely_place_anchor,
    requires_live_location_data,
    resolve_route_anchor,
    route_role_keywords,
    unique_categories,
)
from services.profile_service import (
    DEFAULT_IMPORTED_PROFILE_RECORDS,
    FORBIDDEN_PROFILE_KEYS,
    PROFILE_CONTEXTS,
    build_meituan_context,
    clean_text_list,
    ensure_data,
    find_imported_profile,
    import_request_to_record,
    imported_profile_view,
    imported_record_to_context,
    infer_categories_from_text,
    intent_with_context,
    load_imported_profile_records,
    normalize_profile_mode,
    profile_signal_count,
    profile_with_context,
    resolve_profile_context,
    safe_slug,
    save_imported_profile_record,
    validate_import_payload,
)
from services.route_builder import (
    apply_context_to_candidates,
    build_candidate_view,
    build_dynamic_candidates,
    default_search_selected_pois,
    enrich_route_with_amap_segments,
    poi_to_context_poi,
)
from services.route_insight import (
    build_constraint_conflicts,
    build_follow_up,
    build_follow_up_question,
    build_profile_influence,
    build_route_completeness,
    metric_deltas,
    route_insight,
    route_metrics,
)
from services.trace_service import (
    build_plan_tool_trace,
    build_trace,
    classify_adjustment_with_deepseek,
    trace_step,
)

__all__ = [
    # adjustment_service
    "add_intent_satisfied",
    "adjustment_intent_satisfied",
    "adjustment_search_terms",
    "adjustment_status_for",
    "adjustment_summary",
    "build_changed_stops",
    "choose_add_target",
    "choose_adjustment_target",
    "detect_adjustment_kind",
    "find_adjustment_candidate",
    "has_negative_adjustment",
    "has_reduce_adjustment",
    "is_core_route_stop",
    "mentioned_categories",
    "mentioned_stop_index",
    "objective_improved",
    "parse_adjustment_intent",
    "suggested_relaxations_for",
    # anchor_service
    "categories_for_live_route",
    "city_hint_from",
    "clean_anchor_candidate",
    "context_poi_to_poi",
    "extract_anchor_text",
    "fixed_start_pois_from_route",
    "hard_pinned_pois_for_context",
    "is_likely_place_anchor",
    "requires_live_location_data",
    "resolve_route_anchor",
    "route_role_keywords",
    "unique_categories",
    # profile_service
    "DEFAULT_IMPORTED_PROFILE_RECORDS",
    "FORBIDDEN_PROFILE_KEYS",
    "PROFILE_CONTEXTS",
    "build_meituan_context",
    "clean_text_list",
    "ensure_data",
    "find_imported_profile",
    "import_request_to_record",
    "imported_profile_view",
    "imported_record_to_context",
    "infer_categories_from_text",
    "intent_with_context",
    "load_imported_profile_records",
    "normalize_profile_mode",
    "profile_signal_count",
    "profile_with_context",
    "resolve_profile_context",
    "safe_slug",
    "save_imported_profile_record",
    "validate_import_payload",
    # route_builder
    "apply_context_to_candidates",
    "build_candidate_view",
    "build_dynamic_candidates",
    "default_search_selected_pois",
    "enrich_route_with_amap_segments",
    "poi_to_context_poi",
    # route_insight
    "build_constraint_conflicts",
    "build_follow_up",
    "build_follow_up_question",
    "build_profile_influence",
    "build_route_completeness",
    "metric_deltas",
    "route_insight",
    "route_metrics",
    # trace_service
    "build_plan_tool_trace",
    "build_trace",
    "classify_adjustment_with_deepseek",
    "trace_step",
]
